### ISSUE TITLE
Enable https for the site

### ISSUE THREAD

**Issue by anantoghosh** [KMKfw/kmk_website#10]
Custom domains on github pages has supported https for a while now.
If you're not able to enable https in the settings please check the dns records or try re-adding the domain.
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

Additional help:
https://github.com/orgs/community/discussions/23049

**Comment by claycooper** [comment]
HTTPS has been enabled.

```* Server certificate:
*  subject: CN=kmkfw.io
*  start date: Apr  7 17:15:01 2024 GMT
*  expire date: Jul  6 17:15:00 2024 GMT
*  subjectAltName: host "kmkfw.io" matched cert's "kmkfw.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
````
