### ISSUE TITLE
Discord Invite is invalid

### ISSUE THREAD

**Issue by misel228** [KMKfw/kmk_website#6]
Hello,

the invite link in the website footer is no longer valid. Can you please update it.

Thanks,
Misel

**Comment by claycooper** [comment]
We're working on updating the website's docs.

**Comment by misel228** [comment]
Okay, but is there another way to get the link to join discord?

**Comment by claycooper** [comment]
Sorry, I should have provided that in the last update. The project has switched to Zulip to make it easier for people to get help.

https://kmkfw.zulipchat.com/

**Comment by misel228** [comment]
Thank you! :)

**Comment by claycooper** [comment]
I've merged a new version of the website that includes the correct link to the KMK community.
